### ISSUE TITLE
Issues on image clustering and motion segmentation

### ISSUE THREAD

**Issue by wzkg2012** [t-sakai-kure/R-LSLDGC#1]
The work is impressive, can you publish all the codes?

**Comment by t-sakai-kure** [comment]
We do not have any plan to publish all the codes since it is messy and heavy, and it highly depends on my environment, e..g, the path of the datasets.

However, you can prepare the dataset and preprocess them according to our paper. Then, you just run the code available here, i.e., you just input the data into our method.
For the image dataset, please visit [MNIST](http://yann.lecun.com/exdb/mnist/) or [MNIST (MATLAB format)](https://cs.nyu.edu/~roweis/data.html).
About the motion segmentation dataset, please visit [Hopkins 155](http://www.vision.jhu.edu/data/hopkins155/).
